[project]
name = "handcron"
version = "0.1.0"
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [
    { name = "Tomas Karabela", email = "tkarabela@seznam.cz" },
]
dependencies = [
    "croniter>=6.2.4",
]

[project.optional-dependencies]
postgres = [
    "psycopg>=3.2",
]

[dependency-groups]
dev = [
    "pyrefly>=1.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13"]
build-backend = "uv_build"

[tool.pyrefly]
preset = "strict"

[tool.pytest.ini_options]
testpaths = ["tests"]
